plugins {
    id 'com.android.application'
}

android {
    namespace 'mx.gob.tecoman.vialidad.secure'
    compileSdk 35

    defaultConfig {
        applicationId "mx.gob.tecoman.vialidad.secure"
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName "1.0.1"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
}
